api/urls.py
from django.urls import path, include
from rest_framework import routers
from teams.api.views import TeamViewSet,TeamMemberViewSet, AddTeamMemberView, RemoveTeamMemberView,MakeAdminTeamMemberView,RemoveAdminTeamMemberView, TeamUserView
from projects.api.views import SectionOrderView,TaskOrderView, TaskApprovalView, TaskCompleteView, TaskNoteView, TaskAttachmentView, TaskChoiceView
from organisations.api import views as organisations_api_views
from organisations.api.views import  OrganisationMembersView
from toolchest.api.views import ContactUsView
router = routers.DefaultRouter()
router.register(r'teams', TeamViewSet)
router.register(r'organisations', organisations_api_views.OrganisationViewSet)


urlpatterns = [
    path('team/users/', TeamUserView.as_view()),
    path('task/approve/', TaskApprovalView.as_view()),
    path('task/complete/', TaskCompleteView.as_view()),
    path('task/note/', TaskNoteView.as_view()),
    path('task/attachment/', TaskAttachmentView.as_view()),
    path('task/choices/', TaskChoiceView.as_view()),
    path('reorder/section/', SectionOrderView.as_view()),
    path('reorder/task/', TaskOrderView.as_view()),
    path('organisation/<int:org_id>/members/',OrganisationMembersView.as_view()),
    path('organisation/<int:organisation_id>/team/<int:team_id>/add/', AddTeamMemberView.as_view()),
    path('organisation/<int:organisation_id>/team/<int:team_id>/remove/', RemoveTeamMemberView.as_view()),
    path('make-admin', MakeAdminTeamMemberView.as_view()),
    path('remove-admin', RemoveAdminTeamMemberView.as_view()),
    path('contact-us/',ContactUsView.as_view()),
    path('', include(router.urls)),
]

wfa/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from toolchest import views as toolchest_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('uaa.urls')),
    path('', toolchest_views.site_home, name='site_home'),
    path('contact/', toolchest_views.contact_us, name='contact_us'),
    path('contact/thanks/', toolchest_views.contact_us_thanks, name='contact_us_thanks'),
    path('api/', include('api.urls')),
    path('organisation/', include('organisations.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    from django.views.static import serve
    urlpatterns += (
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
        path('__debug__/', include(debug_toolbar.urls)),

    )

projects/models.py
import os
from django.conf import settings
from django.db import models
from organisations.models import Organisation
from teams.models import Team
from uuid import uuid4


# Create your models here.


"""
PROJECT_STATUS_CHOICES = (('P', 'Pending'), ('S', 'Started'), ('C', 'Complete'))


class Project(models.Model):
    name = models.CharField(max_length=100)
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE)
    reference = models.CharField(max_length=50, blank=True)
    description = models.TextField(max_length=2000, blank=True)
    status = models.CharField(max_length=1, choices=PROJECT_STATUS_CHOICES, default='P')

    # Additional Info
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='project_created_by', on_delete=models.CASCADE)
    modified = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='project_modified_by', on_delete=models.CASCADE)

    def __str__(self):
        return '{} -> {}'.format(self.organisation, self.name)


class ProjectSection(models.Model):
    name = models.CharField(max_length=60)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    order = models.PositiveIntegerField(default=0)

    # Additional Info
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='section_created_by', on_delete=models.CASCADE)
    modified = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='section_modified_by', on_delete=models.CASCADE)

    def __str__(self):
        return '{} -> {}'.format(self.name, self.project)

    class Meta:
        unique_together = ('name', 'project')


PROJECT_TASK_TYPE_CHOICES = (('P', 'Parent'), ('A', 'Approval'), ('G', 'Generic'))
PROJECT_TASK_STATUS_CHOICES = (('P', 'Pending'), ('I', 'In Progress'), ('C', 'Complete'))


class ProjectTask(models.Model):
    name = models.CharField(max_length=60)
    order = models.PositiveIntegerField(default=0)
    description = models.TextField(max_length=2000, blank=True)
    section = models.ForeignKey(ProjectSection, on_delete=models.CASCADE)
    task_type = models.CharField(max_length=1, choices=PROJECT_TASK_TYPE_CHOICES)
    status = models.CharField(max_length=1, choices=PROJECT_TASK_STATUS_CHOICES)
    parent = models.ForeignKey('self', related_name= 'task_parent', blank=True, null=True, on_delete=models.CASCADE)
    dependent_on = models.ForeignKey('self',    related_name= 'task_dependent_on', blank=True, null=True, on_delete=models.CASCADE)
    start_date = models.DateTimeField(blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)
    # TODO: Use actual_start_date and actual_end_date (and rename above fields to target_start_date and target_end_date

    # Assignment Info
    assigned_to_team = models.ForeignKey(Team, blank=True, null=True, on_delete=models.CASCADE)
    assigned_to_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='task_assigned_to_user', blank=True, null=True, on_delete=models.CASCADE)
    assigned_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, related_name='task_assigned_to_by', null=True, on_delete=models.CASCADE)
    assigned_time = models.DateTimeField(blank=True, null=True)

    # Additional Info
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='task_created_by', on_delete=models.CASCADE)
    modified = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='task_modified_by', on_delete=models.CASCADE)

    def __str__(self):
        return '{} - {}'.format(self.id, self.name)





PROJECT_TASK_WORK_TYPE_CHOICES = (('A', 'Approval'), ('G', 'Generic'))



class ProjectTaskWork(models.Model):
    ""/"
    A Task can have multiple work tasks  (this is like a sub-tasks)
    ""/"
    task = models.ForeignKey(ProjectTask, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    work_type = models.CharField(max_length=1, choices=PROJECT_TASK_WORK_TYPE_CHOICES)
    notes = models.TextField(blank=True)

    # Approval Type Related Fields
    approved = models.BooleanField(blank=True, null=True)
    approved_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.CASCADE)

    # Generic Type Related Fields
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='taskwork_created_by',
                                   on_delete=models.CASCADE)
    modified = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='taskwork_modified_by',
                                    on_delete=models.CASCADE)

"""


PROJECT_STATUS_CHOICES = (('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'))


class Project(models.Model):
    name = models.CharField(max_length=100)
    organisation = models.ForeignKey(Organisation, on_delete=models.CASCADE)
    reference = models.CharField(max_length=50, blank=True)
    description = models.TextField(max_length=2000, blank=True)
    status = models.CharField(max_length=10, choices=PROJECT_STATUS_CHOICES, default='PENDING')

    # Additional Info
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='project_created_by', on_delete=models.CASCADE)
    modified = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='project_modified_by', on_delete=models.CASCADE)

    def __str__(self):
        return '{} -> {}'.format(self.organisation, self.name)


class Section(models.Model):
    name = models.CharField(max_length=60)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    order = models.PositiveIntegerField(default=0)

    # Additional Info
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='createdsection_set', on_delete=models.CASCADE)
    modified = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='modifiedsection_set', on_delete=models.CASCADE)

    def __str__(self):
        return '{} -> {}'.format(self.name, self.project)

    class Meta:
        unique_together = ('name', 'project')
        ordering = ('order',)


class Category(models.Model):
    name = models.CharField(max_length=60)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    order = models.PositiveIntegerField(default=0)

    # Additional Info
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='createdcategory_set', on_delete=models.CASCADE)
    modified = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='modifiedcategory_set', on_delete=models.CASCADE)

    def __str__(self):
        return '{} -> {}'.format(self.name, self.project)

    class Meta:
        unique_together = ('name', 'project')
        ordering = ('order',)

class Severity(models.Model):
    name = models.CharField(max_length=60)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    order = models.PositiveIntegerField(default=0)

    # Additional Info
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='createdseverity_set', on_delete=models.CASCADE)
    modified = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='modifiedseverity_set', on_delete=models.CASCADE)

    def __str__(self):
        return '{} -> {}'.format(self.name, self.project)

    class Meta:
        unique_together = ('name', 'project')
        ordering = ('order',)


TASK_TYPE_CHOICES = (('P', 'Parent'), ('A', 'Approval'), ('G', 'Generic'))
TASK_STATUS_CHOICES = (('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'))
#TASK_SEVERITY_CHOICES = (('HIGH', 'High'), ('MEDIUM', 'Medium'), ('Low', 'Low'))


class Task(models.Model):
    """
    Projects are made of tasks
    """
    name = models.CharField(max_length=100)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    category = models.ForeignKey(Category,blank=True, null=True, on_delete=models.CASCADE)
    severity = models.ForeignKey(Severity,blank=True, null=True, on_delete=models.CASCADE)
    type = models.CharField(max_length=1, choices=TASK_TYPE_CHOICES)
    parent = models.ForeignKey('self', related_name='parenttask_set', blank=True, null=True, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=TASK_STATUS_CHOICES)
    dependent_on_section = models.ForeignKey(Section, related_name='dependentsectiontask_set', blank=True, null=True, on_delete=models.CASCADE)
    dependent_on_task = models.ForeignKey('self', related_name='dependenttask_set', blank=True, null=True, on_delete=models.CASCADE)
    duration = models.PositiveIntegerField(default=3, blank=True, null=True,)
    order = models.PositiveIntegerField(default=0)
    reference = models.CharField(max_length=50, blank=True)

    # Capture Dates
    target_start_datetime = models.DateTimeField(blank=True, null=True)
    target_end_datetime = models.DateTimeField(blank=True, null=True)
    actual_start_datetime = models.DateTimeField(blank=True, null=True)
    actual_end_datetime = models.DateTimeField(blank=True, null=True)

    # Assignment Info
    assigned_to_team = models.ForeignKey(Team, blank=True, null=True, on_delete=models.CASCADE)

projects/api/views.py
from rest_framework import viewsets
from rest_framework.views import APIView
from rest_framework import generics
from projects.models import Project, Task, Attachment
from rest_framework.response import Response
from rest_framework import status
from .serializers import (
    SectionOrderSerializer,
    TaskOrderSerializer,
    TaskApprovalSerializer,
    TaskCompleteSerializer,
    TaskNoteSerializer,
    TaskAttachmentSerializer,
    TaskChoiceSerializer,
)
from rest_framework.parsers import FileUploadParser, MultiPartParser, JSONParser, FormParser


class SectionOrderView(generics.GenericAPIView):
    serializer_class = SectionOrderSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({}, status=status.HTTP_201_CREATED)


class TaskOrderView(generics.GenericAPIView):
    serializer_class = TaskOrderSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({}, status=status.HTTP_201_CREATED)


class TaskApprovalView(generics.GenericAPIView):
    serializer_class = TaskApprovalSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        print(request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({}, status=status.HTTP_201_CREATED)


class TaskCompleteView(generics.GenericAPIView):
    serializer_class = TaskCompleteSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({}, status=status.HTTP_201_CREATED)


class TaskNoteView(generics.GenericAPIView):
    serializer_class = TaskNoteSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({}, status=status.HTTP_201_CREATED)


class TaskAttachmentView(generics.GenericAPIView):
    serializer_class = TaskAttachmentSerializer

    # parser_classes = (FormParser, MultiPartParser, FileUploadParser)
    parser_classes = (MultiPartParser,)

    def post(self, request, *args, **kwargs):
        print(request.data)
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        file = request.data['file']
        task_id = request.data.get('task')
        task = Task.objects.get(pk=task_id)
        name = request.data.get('name')
        description = request.data.get('description')

        Attachment.objects.create(
            task=task, file=file, name=name, description=description, created_by=request.user, modified_by=request.user
        )

        #serializer.save()
        return Response({}, status=status.HTTP_201_CREATED)


class TaskChoiceView(generics.ListAPIView):
    serializer_class = TaskChoiceSerializer

    def get_queryset(self,):
        section_id = self.request.GET.get('section_id', None)
        project_id = self.request.GET.get('project_id', None)
        filters = {'section_id': section_id, 'section__project_id': project_id}

        query_set = Task.objects.filter(**filters).exclude(type='P').select_related()
        return query_set

templates/one/projects/add_project.html
{% extends 'base_dashboard.html' %}
{% load crispy_forms_tags %}
{%  block title %}
    Create Project
{% endblock %}
{% block content %}
    <div class="container-fluid shiny-container">
    <div class="row justify-content-center">
        <div class="col-10">
            <form method="post" action="." enctype="multipart/form-data">{% csrf_token %}
                {{ form|crispy }}
                {% if project %}
                    <button type="submit" class="btn btn-success">Update Project</button>
                {% else %}
                    <button type="submit" class="btn btn-success">Create Project</button>
                {% endif %}
                 <a href="javascript:window.history.back()" class="btn btn-secondary float-right">Cancel</a>
            </form>
        </div>
    </div>
    </div>

{% endblock %}

templates/one/projects/change_section.html
{% extends 'base_dashboard.html' %}
{% load crispy_forms_tags %}
{%  block title %}
    Edit Section
{% endblock %}
{% block content %}
    <div class="container-fluid shiny-container">
    <div class="row justify-content-center">
        <div class="col-10">
            <form method="post" action="." enctype="multipart/form-data">{% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Update Section</button>
                <a href="javascript:window.history.back()" class="btn btn-secondary float-right">Cancel</a>
            </form>
        </div>
    </div>
    </div>

{% endblock %}

templates/one/projects/delete_project.html
{% extends 'base_dashboard.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-10">
            <form method="post" action="." enctype="multipart/form-data">{% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Delete Project</button>
                <a href="javascript:window.history.back()" class="btn btn-secondary float-right">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/one/projects/delete_section.html
{% extends 'base_dashboard.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-10">
            <form method="post" action="." enctype="multipart/form-data">{% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Delete Section</button>
                <a href="javascript:window.history.back()" class="btn btn-secondary float-right">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/one/projects/delete_task.html
{% extends 'base_dashboard.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-10">
            <form method="post" action="." enctype="multipart/form-data">{% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Delete Task</button>
                <a href="javascript:window.history.back()" class="btn btn-secondary float-right">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/one/projects/edit_task_error.html
{% extends 'base_dashboard.html' %}
{% block content %}
<h6>You can update only pending tasks.</h6>
{% endblock %}

templates/one/projects/my_tasks.html
{% extends 'base_dashboard.html' %}

{% block content %}
        <div class="container-fluid shiny-container">
            {%comment%}
            <div >
            <a class="btn btn-primary btn-sm active  float-right" href="{% url 'my_tasks'  organisation.slug %}?status=STARTED" role="button">Active</a>
            <a class="btn btn-primary btn-sm  float-right" style ="margin-right: 5px;" href="{% url 'my_tasks'  organisation.slug %}?status=SUCCESS" role="button">Completed</a>
            <a class="btn btn-primary btn-sm  float-right" style ="margin-right: 5px;" href="{% url 'my_tasks'  organisation.slug %}?status=FAILURE" role="button">Failure</a>
            <a class="btn btn-primary btn-sm  float-right" style ="margin-right: 5px;" href="{% url 'my_tasks'  organisation.slug %}">All</a>
            </div>
            {%endcomment%}
            <div class="dropdown float-right" style ="margin-right: 5px;">
              <a class="btn btn-primary btn-sm dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Status
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="{% url 'my_tasks'  organisation.slug %}?status=STARTED">Active</a>
                <a class="dropdown-item" href="{% url 'my_tasks'  organisation.slug %}?status=SUCCESS">Succes</a>
                <a class="dropdown-item" href="{% url 'my_tasks'  organisation.slug %}?status=FAILURE">Failure</a>
                <a class="dropdown-item" href="{% url 'my_tasks'  organisation.slug %}">All</a>
              </div>
            </div>

            <br></br>
                <table class="table" id ="myTasksTable">
                    <thead class="thead-light">
                    <tr>
                        <th>Name</th>
                        <th>Status</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                        <th>Project</th>

                    </tr>
                    </thead>
                    <tbody>

                    {% for task in tasks %}
                        <tr>
                            <td>
                                <a href="{% url 'project_home' task.section.project.organisation.slug task.section.project.id %}">{{ task.name }}</a>
                            </td>
                            <td>
                                {% if task.status == 'STARTED' %}
                                    In Progress
                                {% elif task.status == 'FAILURE' %}
                                    Rejected
                                {% elif task.status == 'SUCCESS' %}
                                    {% if task.type == 'G' %}
                                        Completed
                                    {% elif task.type == 'A' %}
                                        Approved
                                    {% else %}
                                        {{ task.get_status_display }}
                                    {% endif %}
                                {% else %}
                                    {{ task.get_status_display }}
                                {% endif %}

                            </td>
                            <td>{{ task.target_start_datetime }}</td>
                            <td>{{ task.target_end_datetime }}</td>
                            <td>{{ task.section.project.name }}</td>


                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {%comment%}
                <nav aria-label="Pagination">
            <ul class="pagination justify-content-center">
                {% if tasks.has_previous %}
                        <li class="page-item"><a class="page-link" href="{% url 'my_tasks'  organisation.slug %}{% if not tasks.number == 2 %}?page={{ tasks.previous_page_number }}{%if status %}&status={{status}}{%endif%}{%else%}?status={{status}}&page={{ tasks.previous_page_number }}{% endif %}">Previous</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="{% url 'my_tasks'  organisation.slug %}" tabindex="-1">Previous</a></li>
                {% endif %}

                {% for page in paginator.page_range %}
                    {% if page == 1 %}
                        {% if status%}
                            <li class="page-item {% if tasks.number == page %}active{% endif %}"><a class="page-link" href="{% url "my_tasks" organisation.slug %}?status={{status}}">{{ page }}</a></li>
                        {% else %}
                            <li class="page-item {% if tasks.number == page %}active{% endif %}"><a class="page-link" href="{% url "my_tasks" organisation.slug %}">{{ page }}</a></li>
                        {% endif %}
                    {% else %}
                        {% if status%}
                            <li class="page-item {% if tasks.number == page %}active{% endif %}"><a class="page-link" href="{% url "my_tasks" organisation.slug %}?status={{status}}&page={{ page }}">{{ page }}</a></li>
                        {%else%}
                        <li class="page-item {% if tasks.number == page %}active{% endif %}"><a class="page-link" href="{% url "my_tasks" organisation.slug %}?page={{ page }}">{{ page }}</a></li>
                        {% endif %}
                    {% endif %}
                {% endfor %}

                {% if tasks.has_next %}
                    {% if status%}

                        <li class="page-item"><a class="page-link" href="{% url 'my_tasks'  organisation.slug %}?status={{status}}&page={{ tasks.next_page_number }}" aria-label="Next page">Next</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="{% url 'my_tasks'  organisation.slug %}?page={{ tasks.next_page_number }}" aria-label="Next page">Next</a></li>
                    {% endif %}
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="{% url 'my_tasks'  organisation.slug %}?page={{ tasks.number }}" aria-label="Next page">Next</a></li>
                {% endif %}
            </ul>
        </nav>
        {%endcomment%}

            </div>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap4.min.css">
    <style>
        .dataTables_filter label { width: 40%; }
        .dataTables_filter input { width: 80% !important; }
    </style>
{% endblock %}

{% block js %}
    <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap4.min.js"></script>
    <script>
    $(document).ready( function () {
        $('#myTasksTable').DataTable({
            "pageLength": 25,
            "searching": true
            /*language: {
                search: "_INPUT_",
                searchPlaceholder: "Filter Candidates"
            }*/
        });
    } );
    </script>
{% endblock %}

templates/one/projects/task_home.html
{% extends 'base_dashboard.html' %}






{% block content %}
    <div id="task">
        <h3>{{ task.name }}</h3>
        {% if task.parenttask_set %}
            {% for subtask in task.parenttask_set.all %}
                <div id="subtask-{{ subtask.id }}" class="task {{ subtask.status|lower }}">
                    <h4>{{ subtask.name }}</h4>
                    {% with subtask as task %}
                        {% include 'projects/task_home_task.html' %}
                    {% endwith %}
                </div>
            {% endfor %}
        {% else %}
            {% include 'projects/task_home_task.html' %}
        {% endif %}

    </div>


{% endblock %}

templates/one/projects/task_parent_view.html
<div class="row" >
        <div class="col collapse task-details" id="task-parent-{{ task.id }}">
        <hr>
        <form method="post" action="." enctype="multipart/form-data" data-organisation="{{ organisation.slug }}" data-project="{{ project.id }}">{% csrf_token %}

            <div class="row">

                <div class="col-5">

                    <div class="form-group row">
                        <label for="id_status" class="col-4 form ">Status</label>
                        {% if task.status == 'STARTED' %}
                            <input id="id_status" class="col-8 form-control form-control-sm" type="text" placeholder="In Progress" readonly>
                        {% elif task.status == 'FAILURE' %}
                            <input id="id_status" class="col-8 form-control form-control-sm" type="text" placeholder="Rejected" readonly>
                        {% elif task.status == 'SUCCESS' %}
                            {% if task.type == 'G' %}
                                <input id="id_status" class="col-8 form-control form-control-sm" type="text" placeholder="Completed" readonly>
                            {% elif task.type == 'A' %}
                                <input id="id_status" class="col-8 form-control form-control-sm" type="text" placeholder="Approved" readonly>
                            {% else %}
                                <input id="id_status" class="col-8 form-control form-control-sm" type="text" placeholder="{{ task.get_status_display }}" readonly>
                            {% endif %}
                        {% else %}
                            <input id="id_status" class="col-8 form-control form-control-sm" type="text" placeholder="{{ task.get_status_display }}" readonly>
                        {% endif %}
                    </div>


                    <div class="form-group row">
                        <label for="id_task_parent_name" class="col-4 form">Reference</label>
                        <input id="id_task_parent_name" class="col-8 form-control form-control-sm " type="text" placeholder="{{ task.reference }}" readonly>
                    </div>
                </div>

                <div class="col-1"></div>
            
                <div class="col-5">

                    <div class="form-group row">
                        <label for="id_task_parent_category" class="col-4 form">Category</label>
                        <input id="id_task_parent_category" class="col-8 form-control form-control-sm" type="text" placeholder="{{ task.category.name }}" readonly>
                    </div>

                    <div class="form-group row">
                        <label for="id_task_parent_severity" class="col-4 form">Severity</label>
                        <input id="id_task_parent_severity" class="col-8 form-control form-control-sm" type="text" placeholder="{{ task.severity.name }}" readonly>
                    </div>

                </div>
			</div>
		</form>
	</div>
</div>